[phases.setup]
cmds = [
  "curl -fsSL https://deb.nodesource.com/setup_18.x | bash -",
  "apt-get update && apt-get install -y nodejs"
]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm run build || true"]

[start]
cmd = "cd server && npm start"

[providers]
node = "18"